db:
  image: postgres
rabbitmq:
  image: rabbitmq
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - rabbitmq
    - db
    - celery
  env_file:
    - ./defaults.env
    - ./secrets.env
celery:
  build: .
  command: celery --without-gossip --without-mingle --without-heartbeat --app=bills worker -l info
  volumes:
    - .:/code
  links:
    - rabbitmq
    - db
  env_file:
    - ./defaults.env
    - ./secrets.env
