# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-24 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0006_auto_20160123_1816'),
        ('accounts', '0002_account_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_day_of_month', models.IntegerField()),
                ('predicted_amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='accounts.Account')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='transactions.MerchantGroup')),
            ],
        ),
    ]
