# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-24 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringtransaction',
            old_name='merchant',
            new_name='merchant_group',
        ),
    ]
