# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 14:37
from __future__ import unicode_literals

import bills.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('webhook_id', models.CharField(max_length=50, unique=True)),
                ('mondo_account_id', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MondoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mondo_user_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=512, unique=True)),
                ('access_expires', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=512, unique=True)),
                ('user', bills.core.fields.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mondo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
