# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
