# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('decline_reason', models.CharField(max_length=100, null=True)),
                ('is_load', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
