# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_current_balance'),
        ('transactions', '0002_auto_20160123_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account'),
            preserve_default=False,
        ),
    ]
