# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mondo_transaction_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
