# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_mondo_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mondo_transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
