# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_mondo_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='merchant_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.MerchantGroup'),
        ),
    ]
